[workspace]
members = ["torii", "torii-auth-email", "torii-auth-oidc", "torii-core"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/cmackenzie1/torii"
license = "MIT"

[workspace.dependencies]
async-trait = "0.1"
dashmap = "6.1"
futures = "0.3"
regex = "1"
serde = "1"
thiserror = "2"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1", features = ["v4"] }

sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "sqlite",        # TODO: Remove sqlite dependency
    "chrono",
    "uuid",
] }
