[package]
name = "torii-auth-oidc"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
torii-core = { path = "../torii-core" }

jsonwebtoken = "9"

async-trait.workspace = true
serde.workspace = true
sqlx.workspace = true
