[package]
name = "torii"
version = "0.1.1"
description = "A modular authentication ecosystem for Rust applications"
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
torii-core = { path = "../torii-core", version = "0.1.0" }
# TODO: Make optional and add feature flags for each auth plugin
torii-auth-password = { path = "../torii-auth-password", version = "0.1.0" }
torii-auth-oauth = { path = "../torii-auth-oauth", version = "0.1.0" }
torii-auth-passkey = { path = "../torii-auth-passkey", version = "0.1.0" }
torii-storage-sqlite = { path = "../torii-storage-sqlite", version = "0.1.0" }

sqlx = { workspace = true, features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
clap = { version = "4.5.28", features = ["derive"] }
thiserror.workspace = true
serde_json.workspace = true
serde.workspace = true

[dev-dependencies]
tracing-subscriber = { workspace = true }
