[package]
name = "torii"
version = "0.1.1"
description = "A modular authentication ecosystem for Rust applications"
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
