[package]
name = "torii-example-todos"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12"
axum = { version = "0.8", features = ["macros"] }
axum-extra = { version = "0.10", features = ["cookie"] }
chrono = { version = "0.4.39", features = ["serde"] }
dashmap = "6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio"] }
tokio = { version = "1.0", features = ["full"] }
torii-auth-email = { path = "../../torii-auth-email" }
torii-core = { path = "../../torii-core" }
torii-storage-sqlite = { path = "../../torii-storage-sqlite" }
tracing-subscriber = "0.3"
uuid = { version = "1.13.1", features = ["v4", "v7"] }
