[package]
name = "torii-storage-sqlite"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
torii-core = { path = "../torii-core" }
async-trait.workspace = true
sqlx = { workspace = true, default-features = false, features = [
    "runtime-tokio",
    "sqlite",
] }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true
tracing-subscriber.workspace = true
