[package]
name = "torii-core"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
chrono = "0.4.39"
dashmap = "6.1"
downcast-rs = "2.0.1"
futures.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true

[features]
default = []
